# Generated by Django 3.1.7 on 2021-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210316_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('age', models.CharField(max_length=5, verbose_name='Age')),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
